### ISSUE TITLE
hi...  how the NRF24L  connect  esp8266 pins ? 

### ISSUE THREAD

**Issue by xuhongv** [leon-v/MQTT-ESP8266-nRF24L01-Solar-Battery-I-O-Network#5]
hi...  how the NRF24L  connect  esp8266 pins ?

**Comment by leon-v** [comment]
You can check the wiring nets here:
https://easyeda.com/editor#id=51a4e639530d4291a7831a23434c7e45

Feel free to get the PCB printed from there too.

To program, you need to manually pull GPIO0 low while pressing reset.
This can be done while plugged into the ESP01 programmer, or to any USB to 3.3V RS232 adapter.

**Comment by leon-v** [comment]
Let me know if you have any more questions... I need to update the readme with the current state of the project. So any questions would help with writing that.

**Comment by xuhongv** [comment]
good ...  now i build your project , but running  is not succeed !

**Comment by xuhongv** [comment]
I build your project on `ESP8266_RTOS v3.0 SDK`  successfully , but running is not succeed ...  Please tell me how to solve it ?

```
load 0x40100000, len 4336, room 16 
tail 0
chksum 0xef
load 0x00000000, len 0, room 8 
tail 0
chksum 0xef
csum 0xef
csum err
ets_main.c 
```

**Comment by leon-v** [comment]
Is the current SDK 3.0 ? 
Thiis project has a submodule for `https://github.com/espressif/ESP8266_RTOS_SDK`
But i thought that was 2.0 ?

Can you provide more detail on that error? That look to me like you are having issues uploading the binary to the ESP8266. You might need to run `make menuconfig` and update your upload settings ?

**Comment by leon-v** [comment]
This project is not under development currency. I have another product that is more reliable, cheaper, longer range and generally easier.
